name: download

on: 
  workflow_dispatch:

jobs:
  job_2:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success
      - run: ls -R
