# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:  
  
jobs:
  one:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: Dump GitHub context        
        env:
          GITHUB_CONTEXT: ${{ toJSON(env) }}
        run: echo "$GITHUB_CONTEXT"
      
