# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:  
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
     
  dev-deploy:
    needs: test
    runs-on: ubuntu-latest    
    steps:
       - run: echo "dev-deploy"

  prod-deploy:
    runs-on: ubuntu-latest
    needs: dev-deploy
    steps:
    - run: echo "prod-deploy"
