# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
        
env:
  tag: ${{ github.run_id }}-${{ github.sha::7 }}
  
  
jobs:
  job_1:
    name: test
    runs-on: ubuntu-latest
    steps:     
      - name: run echo
        run: echo ${{ env.tag }}

      
