# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:  
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
     
  dev-deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      name: dev
      url: https://test.com
    steps:
       - run: echo "dev-deploy"
       - run: echo ${secrets.ENVARIABLE}

  prod-deploy:
    runs-on: ubuntu-latest
    needs: dev-deploy
    env:
      name: prod
    steps:
    - run: echo "prod-deploy"
