# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      service_version:
        description: Image version
        default: latest
        
env:
  tag: ${{ github.sha }} | cut -c1-8
  
  
jobs:
  job_1:
    name: test
    runs-on: ubuntu-latest
    steps:     
      - name: run echo
        run: echo ${{ github.run_id }}-${{ env.tag }}

      
