# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
        
env:
  tag: ${GITHUB_SHA::7}
  
  
jobs:
  job_1:
    name: test
    runs-on: ubuntu-latest
    steps:     
      - name: run echo
        run: echo ${{ github.run_id }}-${{ env.tag }}

      
