# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      service_version:
        description: Image version
        default: latest
  
jobs:
  one:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: SECRET
        run: echo "${{ secrets.ENVARIABLE }}"
      - name: version
        run: echo "${{ github.event.inputs.service_version }}"

      
