# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:     
      - name: run echo
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "dispatch"
        
      - name: run echo 2
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: echo "not dispatch"
        
      - name: run echo 3
        if: ${{ github.event_name == 'push' }}
        run: echo "push"
        
      - name: run echo 4
        if: ${{ github.event_name != 'push' }}
        run: echo "not push"
        
      - name: run echo call
        uses: stebanmd/learn_by_testing/.github/workflows/test.yml@main


      
