# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:  
  
jobs:
  one:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: SECRET
        run: echo "${{ secrets.ENVARIABLE }}"
      - name: ENV
        run: echo "${{ env.ENVARIABLE }}"

      
